version: '3.8'

services:
  mcp-powerpoint-mistral:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-powerpoint-mistral
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Variables Azure AD - À configurer dans Portainer
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      
      # Configuration du serveur
      - NODE_ENV=production
      - PORT=3000
      - MCP_SERVER_NAME=mcp-powerpoint-mistral
      - MCP_SERVER_VERSION=1.0.0
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logs configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Networks
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

# Volumes pour persistance (optionnel)
volumes:
  mcp_logs:
    driver: local